package lk.tcs.util;

public enum ModuleList {
    EMPLOYEE, USER,USERSTATUS, PRIVILAGE, DESIGNATION,EMPLOYEESTATUS, USERPASSWORDCHANGE,CUSTOMER,ITEM,SUPPLIER,SELL,PORDER,GOODRECIVE,DISPOSAL,RETURNITEM,SERVICELINE,
    SERVICEREQUEST,SERVICE,COMPANY,WARRANTYSERVICE,CATEGORY,SUBCATEGORY,BRAND,UNIT,SMS
}
